// Home: a link list, no data. Everything interesting is on the routes it points at.
export default function HomePage() {
  return (
    <div style={{ maxWidth: 720, margin: '2rem auto', fontFamily: 'system-ui, sans-serif', lineHeight: 1.6 }}>
      <h1 style={{ marginTop: 0 }}>vike-crud example</h1>
      <p>
        One <code>defineSchema('posts')</code> drives a full CRUD page -- zero bespoke UI code. The schema is the intent,
        the view is derived.
      </p>
      <ul>
        <li>
          <a href="/posts">/posts</a> -- a <strong>generated</strong> resource from one <code>defineResource({'{ table: "posts" }'})</code>,
          owner-scoped reads and writes. <code>mode: 'dialog'</code>: a list, with view / create / edit opening as dialogs
          over it. There is no page component for it.
        </li>
        <li>
          <a href="/posts-route">/posts-route</a> -- the same resource in <code>mode: 'route'</code>: the list links each row
          to its own detail page (<code>/posts-route/@id</code>, <code>/new</code>, <code>/@id/edit</code>).
        </li>
        <li>
          <a href="/inline">/inline</a> -- the same <code>posts</code> block dropped into a <strong>hand-written</strong>{' '}
          vike-react page (no page-gen). Proves the blocks are composable, not lock-in.
        </li>
        <li>
          <a href="/posts-ejected">/posts-ejected</a> -- the generated view after an <strong>eject</strong>: the whole page
          (data hook + view descriptor + owner-scope) written out to <code>pages/posts-ejected/</code> as plain, owned
          source. Same list + create form, but nothing regenerates -- generated by <code>ejectView(view)</code>.
        </li>
        <li>
          <a href="/actions-demo">/actions-demo</a> -- an <strong>owner-guarded action</strong>: a <code>Publish</code>{' '}
          button (a vike-blocks action block) POSTs <code>/_actions/publish</code>, flips the row, and fires a toast.
          Wired with <code>vike-actions</code>.
        </li>
      </ul>
    </div>
  )
}
